apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: glusterfs-client
provisioner: cluster.local/glusterfs # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"
